### ISSUE TITLE
'NoneType' object has no attribute 'attrs' for Oxford City Council

### ISSUE THREAD

**Issue by PeterHaban** [robbrad/UKBinCollectionData#1393]
### Name of Council

OxfordCityCouncil

### Issue Information

I've just tried this integration for OxfordCityCouncil with the following details:
UPRN: 100120809445
Postcode: OX3 0AZ

but get the following error in HA: Failed setup, will retry: Unexpected error: 'NoneType' object has no attribute 'attrs'

I've fished the webform out of OxfordCityCouncil.py and if I go to https://www.oxford.gov.uk/xfp/form/142 I get the right information for my Postcode and house number.
Any chance you might be able to point me in the right direction as to what I might be doing wrong?

Thanks,
Peter

### Verification

- [x] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [x] I have checked my address/postcode/UPRN works on the council's website
- [x] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [x] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by m26dvd** [comment]
Looks like a slight change to the Oxford council website.

Fixed in my latest commit

**Comment by PeterHaban** [comment]
Lovely, thanks for getting a fix in. I've updated to v0.152.0 which I assume comes with that fix? When I try it with the following I'm still getting the same error, can you help me figure out where I'm going wrong?

URL to fetch bin collection data
https://www.oxford.gov.uk
UPRN (Unique Property Reference Number)
100120809445
Postcode of the address
OX3 0AZ
The time in seconds for how long the sensor should wait for data
60
Time in hours between updates
12

Kind Regards,
Peter

**Comment by PeterHaban** [comment]
Latest version has just come through with the fix and seems to be working ok now. Thanks for all your help.
